# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BINARY_TZ "ON")
set(CPACK_BUILD_SOURCE_DIRS "/home/aleksandr/QGC/qgroundcontrol_orig;/home/aleksandr/QGC/qgroundcontrol_orig/build_manual")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/home/aleksandr/Qt/Tools/CMake/share/cmake-3.30/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "QGroundControl built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_GENERATOR "TGZ")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/aleksandr/QGC/qgroundcontrol_orig/build_manual;QGroundControl;ALL;/")
set(CPACK_INSTALL_PREFIX "/home/aleksandr/QGC/qgroundcontrol_orig/build_manual/AppDir/usr")
set(CPACK_MODULE_PATH "/home/aleksandr/Qt/6.8.3/gcc_arm64/lib/cmake/Qt6/platforms;/home/aleksandr/QGC/qgroundcontrol_orig/cmake;/home/aleksandr/QGC/qgroundcontrol_orig/cmake/modules;/home/aleksandr/QGC/qgroundcontrol_orig/cmake/find-modules;/home/aleksandr/Qt/6.8.3/gcc_arm64/lib/cmake/Qt6;/home/aleksandr/Qt/6.8.3/gcc_arm64/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/aleksandr/Qt/6.8.3/gcc_arm64/lib/cmake/Qt6/3rdparty/kwin;/home/aleksandr/Qt/6.8.3/gcc_arm64/lib/cmake/Qt6;/home/aleksandr/Qt/6.8.3/gcc_arm64/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;/home/aleksandr/Qt/6.8.3/gcc_arm64/lib/cmake/Qt6/3rdparty/kwin")
set(CPACK_NSIS_DISPLAY_NAME "GeographicLib-2.5")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "GeographicLib-2.5")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/aleksandr/QGC/qgroundcontrol_orig/build_manual/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "karney@alum.mit.edu")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/home/aleksandr/Qt/Tools/CMake/share/cmake-3.30/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "GeographicLib library, utilities, and documentation")
set(CPACK_PACKAGE_FILE_NAME "QGroundControl-2.5-Linux")
set(CPACK_PACKAGE_HOMEPAGE_URL "qgroundcontrol.com")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "GeographicLib-2.5")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "GeographicLib-2.5")
set(CPACK_PACKAGE_NAME "QGroundControl")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "GeographicLib")
set(CPACK_PACKAGE_VERSION "2.5")
set(CPACK_PACKAGE_VERSION_MAJOR "2")
set(CPACK_PACKAGE_VERSION_MINOR "5")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(CPACK_READELF_EXECUTABLE "/usr/bin/readelf")
set(CPACK_RESOURCE_FILE_LICENSE "/home/aleksandr/QGC/qgroundcontrol_orig/build_manual/cpm_modules/geographiclib/9b427b28c42ccd9514fdbdfc56310bccb9a90d0c/LICENSE.txt")
set(CPACK_RESOURCE_FILE_README "/home/aleksandr/Qt/Tools/CMake/share/cmake-3.30/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/home/aleksandr/Qt/Tools/CMake/share/cmake-3.30/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TGZ;ZIP")
set(CPACK_SOURCE_IGNORE_FILES "#;~$;/\\.git;/home/aleksandr/QGC/qgroundcontrol_orig/build_manual/cpm_modules/geographiclib/9b427b28c42ccd9514fdbdfc56310bccb9a90d0c/BUILD;/home/aleksandr/QGC/qgroundcontrol_orig/build_manual/cpm_modules/geographiclib/9b427b28c42ccd9514fdbdfc56310bccb9a90d0c/man/(.*\\.pod|makeusage\\.sh|dummy\\..*)$;/home/aleksandr/QGC/qgroundcontrol_orig/build_manual/cpm_modules/geographiclib/9b427b28c42ccd9514fdbdfc56310bccb9a90d0c/cmake/maintainer-.*\\.cmake$;/home/aleksandr/QGC/qgroundcontrol_orig/build_manual/cpm_modules/geographiclib/9b427b28c42ccd9514fdbdfc56310bccb9a90d0c/(develop|cgi-bin|.*\\.cache)/;/home/aleksandr/QGC/qgroundcontrol_orig/build_manual/cpm_modules/geographiclib/9b427b28c42ccd9514fdbdfc56310bccb9a90d0c/(data-distrib|data-installer)/;/home/aleksandr/QGC/qgroundcontrol_orig/build_manual/cpm_modules/geographiclib/9b427b28c42ccd9514fdbdfc56310bccb9a90d0c/(archive|scratch|mpfr_mpir_x86_x64_msvc2010)/;/home/aleksandr/QGC/qgroundcontrol_orig/build_manual/cpm_modules/geographiclib/9b427b28c42ccd9514fdbdfc56310bccb9a90d0c/.*\\.(zip|tar\\.gz|bak|lsp)$;/home/aleksandr/QGC/qgroundcontrol_orig/build_manual/cpm_modules/geographiclib/9b427b28c42ccd9514fdbdfc56310bccb9a90d0c/(autogen|biblio)\\.sh$;/home/aleksandr/QGC/qgroundcontrol_orig/build_manual/cpm_modules/geographiclib/9b427b28c42ccd9514fdbdfc56310bccb9a90d0c/(makefile-admin|HOWTO-RELEASE.txt)$")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/aleksandr/QGC/qgroundcontrol_orig/build_manual/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "GeographicLib-2.5")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_SYSTEM_NAME "Linux")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "Linux")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/aleksandr/QGC/qgroundcontrol_orig/build_manual/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
